name: Tests

on:
  push:
  pull_request:

jobs:

  test:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4


      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20


      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run smoke tests
        run: npm run test:smoke


      - name: Run regression tests
        if: github.ref == 'refs/heads/main'
        run: npm run test:regression


      - name: Upload report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: mochawesome-report
          path: mochawesome-report/
          if-no-files-found: ignore